// chaos-tauri/src/app/components/DanmakuList.svelte
<script lang="ts">
  import { onDestroy, onMount } from 'svelte'

  import { createDanmakuListStore, type DanmakuListStore } from '@/danmaku/store'

  export let maxItems: number = 400
  export let emptyText: string = '等待弹幕...'
  export let stickToBottom: boolean = false
  export let onOpenUrl: ((url: string) => void) | undefined = undefined

  // Two-way bound so parents can call `store.enqueue(...)` / `store.clear()`.
  export let store: DanmakuListStore | null = null

  let scrollEl: HTMLElement | null = null
  let listEl: HTMLElement | null = null
  let statusEl: HTMLElement | null = null
  let count = 0

  onMount(() => {
    if (!scrollEl || !listEl) return
    store = createDanmakuListStore({
      scrollEl,
      listEl,
      statusEl: statusEl ?? undefined,
      maxItems,
      stickToBottom,
      onOpenUrl,
      afterFlush: (c) => {
        count = c
      }
    })
  })

  onDestroy(() => {
    store?.dispose()
    store = null
  })
</script>

<div class="panel dm-panel">
  {#if count === 0}
    <div class="empty">{emptyText}</div>
  {/if}
  <div bind:this={statusEl} class="text-muted"></div>
  <div bind:this={scrollEl} class="dm-scroll">
    <div bind:this={listEl} class="dm-list"></div>
  </div>
</div>

// chaos-tauri/src/app/components/DanmakuList.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue'

import { createDanmakuListStore, type DanmakuListStore } from '@/danmaku/store'
import type { DanmakuUiMessage } from '@/shared/types'

type Exposed = {
  enqueue(msg: DanmakuUiMessage): void
  clear(): void
}

const props = withDefaults(
  defineProps<{
    maxItems?: number
    emptyText?: string
    stickToBottom?: boolean
    onOpenUrl?: (url: string) => void
  }>(),
  {
    maxItems: 400,
    emptyText: '等待弹幕...',
    stickToBottom: false
  }
)

const scrollEl = ref<HTMLElement | null>(null)
const listEl = ref<HTMLElement | null>(null)
const statusEl = ref<HTMLElement | null>(null)
const emptyEl = ref<HTMLElement | null>(null)

let store: DanmakuListStore | null = null

onMounted(() => {
  if (!scrollEl.value || !listEl.value) return
  store = createDanmakuListStore({
    scrollEl: scrollEl.value,
    listEl: listEl.value,
    statusEl: statusEl.value ?? undefined,
    maxItems: props.maxItems,
    stickToBottom: props.stickToBottom,
    onOpenUrl: props.onOpenUrl,
    afterFlush: (count) => {
      if (!emptyEl.value) return
      emptyEl.value.style.display = count > 0 ? 'none' : ''
    }
  })
})

onBeforeUnmount(() => {
  store?.dispose()
  store = null
})

function enqueue(msg: DanmakuUiMessage) {
  store?.enqueue(msg)
}

function clear() {
  store?.clear()
  if (emptyEl.value) emptyEl.value.style.display = ''
}

defineExpose<Exposed>({ enqueue, clear })
</script>

<template>
  <div class="panel dm-panel">
    <div ref="emptyEl" class="empty">{{ props.emptyText }}</div>
    <div ref="statusEl" class="text-muted" />
    <div ref="scrollEl" class="dm-scroll">
      <div ref="listEl" class="dm-list" />
    </div>
  </div>
</template>
