// chaos-tauri/src/app/pages/SettingsPage.svelte
<script lang="ts">
  import { invoke } from '@tauri-apps/api/core'

  import { prefs } from '@/stores/prefs'
  import type { BackdropMode, OverlayMode, ThemeMode } from '@/shared/prefs'

  function readSelectValue(ev: Event): string {
    return ((ev.target as unknown as { value: string })?.value ?? '').toString()
  }

  function onThemeChange(ev: Event) {
    const v = readSelectValue(ev) as ThemeMode
    prefs.setThemeMode(v)
  }

  function onOverlayChange(ev: Event) {
    const v = readSelectValue(ev) as OverlayMode
    prefs.setOverlayMode(v)
  }

  function onBackdropChange(ev: Event) {
    const v = readSelectValue(ev) as BackdropMode
    prefs.setBackdropMode(v)
    // Best-effort: apply immediately on Windows; no-op elsewhere.
    void invoke('set_backdrop', { mode: v }).catch(() => {})
  }
</script>

<div class="page page-narrow">
  <h2 class="heading">设置</h2>
  <div class="text-secondary">提示：主题/侧边栏折叠状态/Overlay 模式/Backdrop 会自动持久化。</div>

  <fluent-card class="app-card">
    <div class="card-pad settings-grid">
      <div class="settings-row">
        <div class="field-label">主题</div>
        <fluent-select class="select" value={$prefs.themeMode} on:change={onThemeChange}>
          <fluent-option value="system">跟随系统</fluent-option>
          <fluent-option value="light">浅色主题</fluent-option>
          <fluent-option value="dark">深色主题</fluent-option>
        </fluent-select>
      </div>

      <div class="settings-row">
        <div class="field-label">Overlay 模式</div>
        <fluent-select class="select" value={$prefs.overlayMode} on:change={onOverlayChange}>
          <fluent-option value="transparent">透明（可能不稳定）</fluent-option>
          <fluent-option value="opaque">不透明（更稳，推荐）</fluent-option>
        </fluent-select>
      </div>

      <div class="settings-row">
        <div class="field-label">Backdrop（Win11）</div>
        <fluent-select class="select" value={$prefs.backdropMode} on:change={onBackdropChange}>
          <fluent-option value="mica">Mica（更像原生）</fluent-option>
          <fluent-option value="none">关闭（更稳）</fluent-option>
        </fluent-select>
      </div>

      <div class="text-muted">
        说明：透明 Overlay 在某些机器/驱动下可能更吃性能；如果出现掉帧/卡顿，改为“不透明（更稳）”。<br />
        Backdrop 仅对 Windows 生效；若出现发虚/卡顿可关闭。
      </div>
    </div>
  </fluent-card>
</div>

// chaos-tauri/src/app/pages/SettingsPage.vue
<script setup lang="ts">
import { usePrefsStore } from '@/stores/prefs'
import type { OverlayMode, ThemeMode } from '@/shared/prefs'

const prefs = usePrefsStore()

function onThemeChange(ev: Event) {
  const v = (ev.target as unknown as { value: string }).value as ThemeMode
  prefs.setThemeMode(v)
}

function onOverlayChange(ev: Event) {
  const v = (ev.target as unknown as { value: string }).value as OverlayMode
  prefs.setOverlayMode(v)
}
</script>

<template>
  <div class="page page-narrow">
    <h2 class="heading">设置</h2>
    <div class="text-secondary">提示：主题/侧边栏折叠状态/Overlay 模式会自动持久化。</div>

    <fluent-card class="app-card">
      <div class="card-pad settings-grid">
        <div class="settings-row">
          <div class="field-label">主题</div>
          <fluent-select class="select" :value="prefs.themeMode" @change="onThemeChange">
            <fluent-option value="system">跟随系统</fluent-option>
            <fluent-option value="light">浅色主题</fluent-option>
            <fluent-option value="dark">深色主题</fluent-option>
          </fluent-select>
        </div>

        <div class="settings-row">
          <div class="field-label">Overlay 模式</div>
          <fluent-select class="select" :value="prefs.overlayMode" @change="onOverlayChange">
            <fluent-option value="transparent">透明（默认）</fluent-option>
            <fluent-option value="opaque">不透明（更稳）</fluent-option>
          </fluent-select>
        </div>

        <div class="text-muted">
          说明：透明 Overlay 在某些机器/驱动下可能更吃性能；如果出现掉帧/卡顿，改为“不透明（更稳）”。
        </div>
      </div>
    </fluent-card>
  </div>
</template>
